// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -source=client.go -destination=mockhttpx/client_mock.go -package=mockhttpx
//

// Package mockhttpx is a generated GoMock package.
package mockhttpx

import (
	context "context"
	reflect "reflect"

	httpx "github.com/wwwangxc/gopkg/httpx"
	gomock "go.uber.org/mock/gomock"
)

// MockClientProxy is a mock of ClientProxy interface.
type MockClientProxy struct {
	ctrl     *gomock.Controller
	recorder *MockClientProxyMockRecorder
	isgomock struct{}
}

// MockClientProxyMockRecorder is the mock recorder for MockClientProxy.
type MockClientProxyMockRecorder struct {
	mock *MockClientProxy
}

// NewMockClientProxy creates a new mock instance.
func NewMockClientProxy(ctrl *gomock.Controller) *MockClientProxy {
	mock := &MockClientProxy{ctrl: ctrl}
	mock.recorder = &MockClientProxyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientProxy) EXPECT() *MockClientProxyMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockClientProxy) Delete(ctx context.Context, url string, dest any, opts ...httpx.RequestOption) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, url, dest}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockClientProxyMockRecorder) Delete(ctx, url, dest any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, url, dest}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockClientProxy)(nil).Delete), varargs...)
}

// Do mocks base method.
func (m *MockClientProxy) Do(ctx context.Context, req httpx.RequestProtocol, dest any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", ctx, req, dest)
	ret0, _ := ret[0].(error)
	return ret0
}

// Do indicates an expected call of Do.
func (mr *MockClientProxyMockRecorder) Do(ctx, req, dest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockClientProxy)(nil).Do), ctx, req, dest)
}

// Get mocks base method.
func (m *MockClientProxy) Get(ctx context.Context, url string, dest any, opts ...httpx.RequestOption) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, url, dest}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockClientProxyMockRecorder) Get(ctx, url, dest any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, url, dest}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockClientProxy)(nil).Get), varargs...)
}

// Head mocks base method.
func (m *MockClientProxy) Head(ctx context.Context, url string, dest any, opts ...httpx.RequestOption) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, url, dest}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Head", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Head indicates an expected call of Head.
func (mr *MockClientProxyMockRecorder) Head(ctx, url, dest any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, url, dest}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Head", reflect.TypeOf((*MockClientProxy)(nil).Head), varargs...)
}

// Options mocks base method.
func (m *MockClientProxy) Options(ctx context.Context, url string, dest any, opts ...httpx.RequestOption) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, url, dest}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Options", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Options indicates an expected call of Options.
func (mr *MockClientProxyMockRecorder) Options(ctx, url, dest any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, url, dest}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Options", reflect.TypeOf((*MockClientProxy)(nil).Options), varargs...)
}

// Patch mocks base method.
func (m *MockClientProxy) Patch(ctx context.Context, url string, dest any, opts ...httpx.RequestOption) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, url, dest}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Patch", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Patch indicates an expected call of Patch.
func (mr *MockClientProxyMockRecorder) Patch(ctx, url, dest any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, url, dest}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Patch", reflect.TypeOf((*MockClientProxy)(nil).Patch), varargs...)
}

// Post mocks base method.
func (m *MockClientProxy) Post(ctx context.Context, url string, dest any, opts ...httpx.RequestOption) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, url, dest}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Post", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Post indicates an expected call of Post.
func (mr *MockClientProxyMockRecorder) Post(ctx, url, dest any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, url, dest}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Post", reflect.TypeOf((*MockClientProxy)(nil).Post), varargs...)
}

// Put mocks base method.
func (m *MockClientProxy) Put(ctx context.Context, url string, dest any, opts ...httpx.RequestOption) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, url, dest}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Put", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Put indicates an expected call of Put.
func (mr *MockClientProxyMockRecorder) Put(ctx, url, dest any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, url, dest}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockClientProxy)(nil).Put), varargs...)
}
