// Code generated by MockGen. DO NOT EDIT.
// Source: fetcher.go

// Package mockredis is a generated GoMock package.
package mockredis

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	redis "github.com/wwwangxc/gopkg/redis"
	reflect "reflect"
)

// MockFetcherProxy is a mock of FetcherProxy interface
type MockFetcherProxy struct {
	ctrl     *gomock.Controller
	recorder *MockFetcherProxyMockRecorder
}

// MockFetcherProxyMockRecorder is the mock recorder for MockFetcherProxy
type MockFetcherProxyMockRecorder struct {
	mock *MockFetcherProxy
}

// NewMockFetcherProxy creates a new mock instance
func NewMockFetcherProxy(ctrl *gomock.Controller) *MockFetcherProxy {
	mock := &MockFetcherProxy{ctrl: ctrl}
	mock.recorder = &MockFetcherProxyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockFetcherProxy) EXPECT() *MockFetcherProxyMockRecorder {
	return m.recorder
}

// Fetch mocks base method
func (m *MockFetcherProxy) Fetch(ctx context.Context, key string, dest interface{}, opts ...redis.FetchOption) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, key, dest}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Fetch", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Fetch indicates an expected call of Fetch
func (mr *MockFetcherProxyMockRecorder) Fetch(ctx, key, dest interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, key, dest}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fetch", reflect.TypeOf((*MockFetcherProxy)(nil).Fetch), varargs...)
}
