// Code generated by MockGen. DO NOT EDIT.
// Source: locker.go

// Package mockredis is a generated GoMock package.
package mockredis

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	redis "github.com/wwwangxc/gopkg/redis"
	reflect "reflect"
)

// MockLockerProxy is a mock of LockerProxy interface
type MockLockerProxy struct {
	ctrl     *gomock.Controller
	recorder *MockLockerProxyMockRecorder
}

// MockLockerProxyMockRecorder is the mock recorder for MockLockerProxy
type MockLockerProxyMockRecorder struct {
	mock *MockLockerProxy
}

// NewMockLockerProxy creates a new mock instance
func NewMockLockerProxy(ctrl *gomock.Controller) *MockLockerProxy {
	mock := &MockLockerProxy{ctrl: ctrl}
	mock.recorder = &MockLockerProxyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockLockerProxy) EXPECT() *MockLockerProxyMockRecorder {
	return m.recorder
}

// LockAndCall mocks base method
func (m *MockLockerProxy) LockAndCall(ctx context.Context, key string, f func() error, opts ...redis.LockOption) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, key, f}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "LockAndCall", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// LockAndCall indicates an expected call of LockAndCall
func (mr *MockLockerProxyMockRecorder) LockAndCall(ctx, key, f interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, key, f}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockAndCall", reflect.TypeOf((*MockLockerProxy)(nil).LockAndCall), varargs...)
}

// TryLock mocks base method
func (m *MockLockerProxy) TryLock(ctx context.Context, key string, opts ...redis.LockOption) (string, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, key}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "TryLock", varargs...)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TryLock indicates an expected call of TryLock
func (mr *MockLockerProxyMockRecorder) TryLock(ctx, key interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, key}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TryLock", reflect.TypeOf((*MockLockerProxy)(nil).TryLock), varargs...)
}

// Lock mocks base method
func (m *MockLockerProxy) Lock(ctx context.Context, key string, opts ...redis.LockOption) (string, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, key}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Lock", varargs...)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Lock indicates an expected call of Lock
func (mr *MockLockerProxyMockRecorder) Lock(ctx, key interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, key}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Lock", reflect.TypeOf((*MockLockerProxy)(nil).Lock), varargs...)
}

// Unlock mocks base method
func (m *MockLockerProxy) Unlock(ctx context.Context, key, uuid string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unlock", ctx, key, uuid)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unlock indicates an expected call of Unlock
func (mr *MockLockerProxyMockRecorder) Unlock(ctx, key, uuid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unlock", reflect.TypeOf((*MockLockerProxy)(nil).Unlock), ctx, key, uuid)
}
